### ISSUE TITLE
Causing massive conflicting errors with ULX/Ulib

### ISSUE THREAD

**Issue by CptHaxray** [Guardian954/TTT2-CustomRolesPort#1]
Heyo. I've recently tried installing 3 of these roles onto my server (Clown, Killer Clown, and Beggar) and upon adding them Ulib started spitting out lua errors. This resulted in the entire TTT2 settings section of the Ulx menu to disappear, and a lot of other commands to stop functioning among other issues.

Heres the issue i got in console, I hope you can sort out whatever caused this as I really wanted to use these roles.

[ulx] lua/vgui/dnumberscratch.lua:156: attempt to concatenate local 'iDecimals' (a boolean value)
    1. GetTextValue - lua/vgui/dnumberscratch.lua:156
        2. ValueChanged - lua/vgui/dnumslider.lua:184
            3. SetDecimals - lua/vgui/dnumslider.lua:138
                4. makeslider - addons/ulx/lua/ulx/modules/cl/xlib.lua:543
                    5. unknown - addons/ulx_modules/lua/ulx/xgui/gamemodes/terrortown.lua:450
                        6. include - [C]:-1
                            7. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:157
                                8. Call - addons/ulib/lua/ulib/shared/hook.lua:109
                                    9. fn - addons/ulib/lua/ulib/cl_init.lua:49
                                        10. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by CptHaxray** [comment]
Update on this issue:

I tried reinstalling with all of the roles. No Lua errors appeared, but the TTT2 settings section of ULX went completely blank still, except for  Round Structure. Something is wrong with the way your convars are set-up.

**Comment by CptHaxray** [comment]
Second Update:

Upon changing the known broken clown convar (the Decimal in the  clown_health_on_transform section being set to = true), i'm still getting the issue where almost all of the settings in the TTT2 tab disappears.

**Comment by Guardian954** [comment]
Pushed an update with all the roles working and adjustable via ulx on my server, let me know if it works for you now please

**Comment by CptHaxray** [comment]
The main issue is no longer occuring, however a similarly related issue now is.

Two times while using the roles, suddenly all ulx command print outs broke, including the @ admin chat command. The commands still functioned but the chat print broke. This happened mid-round multiple times, and fixes on map change. The only thing that was changed was reintroducing your roles. I am currently using the Beggar and Clown, and none of the others. My only assumption is it has to do with either the Beggar or Clown dying mid round, or the Clown's transformation into evil clown triggering.

**Comment by Guardian954** [comment]
I was doing unnecessary things in the revive that TTT2 already did which might've been the cause, can you please see if the latest version fixes your issue?
