### ISSUE TITLE
Conflicts with Pharaoh Role Due to Abbrivation

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [Guardian954/TTT2-CustomRolesPort#2]
Because both Pharaoh and Phantom uses the same "pha" abbreviations, there is a conflict which will override things and cause corruption.

**Comment by Guardian954** [comment]
Just pushed an update changing the Phantom to phn to avoid this issue

**Comment by BDJslime-UnaverageJoe** [comment]
Confirmed, bug is fixed after new commit and clearing cache.
